name: Get ETH Balances

on:
  # Schedule to run twice a day (at 14:00 and 22:00 UTC)
  schedule:
    - cron: '0 14,22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch-balances:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run balance script
        env:
          INFURA_URL: ${{ secrets.INFURA_URL }}
        run: python scripts/get_balances.py

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update ETH balances report"
          # The pattern of the files to commit.
          file_pattern: "results/*.csv"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"